# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from donor_db_update import Ui_DonorDetailsForm


class Ui_Form222(object):
    def setupUi(self, Form222):
        Form222.setObjectName("Form222")
        Form222.resize(800, 600)
        self.label = QtWidgets.QLabel(Form222)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("11.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form222)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(198,44,126)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form222)
        self.label_3.setGeometry(QtCore.QRect(80, 280, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0,0,0);background-color: rgb(255,255,255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form222)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0,0,0);background-color: rgb(255,255,255)")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form222)
        self.lineEdit.setGeometry(QtCore.QRect(350, 190, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form222)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form222)
        self.pushButton.setGeometry(QtCore.QRect(570, 490, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(88,202,250);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.next_page)

        self.lineEdit_6 = QtWidgets.QLineEdit(Form222)
        self.lineEdit_6.setGeometry(QtCore.QRect(260, 450, 281, 51))
        self.lineEdit_6.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
                                    "border:none;\n"
                                    "border-bottom:2px solid rgba(255,255,255,255);\n"
                                    "color: rgb(0,0,0);\n"
                                    "paddin-bottom:7px;\n"
                                    "font: 24pt \"MS Shell Dlg 2\";\n"
                                    "")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form222)
        self.lineEdit_21.setGeometry(QtCore.QRect(260, 500, 281, 51))
        self.lineEdit_21.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
                                      "border:none;\n"
                                      "border-bottom:2px solid rgba(255,255,255,255);\n"
                                      "color: rgb(0,0,0);\n"
                                      "paddin-bottom:7px;\n"
                                      "font: 24pt \"MS Shell Dlg 2\";\n"
                                      "")
        self.lineEdit_21.setObjectName("lineEdit_21")

        self.retranslateUi(Form222)
        QtCore.QMetaObject.connectSlotsByName(Form222)
        Form222.setWindowTitle("Donor login")


    def retranslateUi(self, Form222):
        _translate = QtCore.QCoreApplication.translate
        Form222.setWindowTitle(_translate("Form2", "Form"))
        self.label_2.setText(_translate("Form2", "LOG IN "))
        self.label_3.setText(_translate("Form2", "PASSWORD:"))
        self.label_4.setText(_translate("Form2", "USER_NAME:"))
        self.pushButton.setText(_translate("Form2", "LOG IN"))


    def next_page(self):
        n1 = self.lineEdit.text()
        n2 = self.lineEdit_2.text()
        if n1 == 'donor':
            print("correct username")
            self.lineEdit_6.setText("correct username")
            if n2 == '123':
                print("correct password")
                self.lineEdit_21.setText("correct password")
                self.DonorDetailsForm = QtWidgets.QMainWindow()
                self.ui = Ui_DonorDetailsForm()
                self.ui.setupUi(self.DonorDetailsForm)
                self.DonorDetailsForm.show()
            else:
                print("wrong password")
                self.lineEdit_21.setText("wrong password")
        else:
            print("wrong username")
            self.lineEdit_6.setText("wrong username")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form222 = QtWidgets.QWidget()
    ui = Ui_Form222()
    ui.setupUi(Form222)
    Form222.show()
    sys.exit(app.exec_())
