# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from patient_db_view import Ui_Form12

class Ui_Form22(object):
    def setupUi(self, Form22):
        Form22.setObjectName("Form22")
        Form22.resize(800,600)
        self.label = QtWidgets.QLabel(Form22)
        self.label.setGeometry(QtCore.QRect(0, 0, 800,600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("666.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form22)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(198,44,126)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form22)
        self.label_3.setGeometry(QtCore.QRect(150, 280, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0,0,0);;background-color: rgb(255,255,255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form22)
        self.label_4.setGeometry(QtCore.QRect(150, 190, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0,0,0);;background-color: rgb(255,255,255)")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form22)
        self.lineEdit.setGeometry(QtCore.QRect(450, 190, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form22)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form22)
        self.pushButton.setGeometry(QtCore.QRect(570, 490, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(88,202,250);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.next_page)


        self.lineEdit_21 = QtWidgets.QLineEdit(Form22)
        self.lineEdit_21.setGeometry(QtCore.QRect(260, 400, 381, 51))
        self.lineEdit_21.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
                                      "border:none;\n"
                                      "border-bottom:2px solid rgba(255,255,255,255);\n"
                                      "color: rgb(255,255,255);\n"
                                      "paddin-bottom:7px;\n"
                                      "font: 24pt \"MS Shell Dlg 2\";\n"
                                      "")
        self.lineEdit_21.setObjectName("lineEdit_21")

        self.retranslateUi(Form22)
        QtCore.QMetaObject.connectSlotsByName(Form22)
        Form22.setWindowTitle("Login")


    def retranslateUi(self, Form22):
        _translate = QtCore.QCoreApplication.translate
        Form22.setWindowTitle(_translate("Form2", "Form"))
        self.label_2.setText(_translate("Form2", " LOG IN "))
        self.label_3.setText(_translate("Form2", "PASSWORD:"))
        self.label_4.setText(_translate("Form2", "USER_NAME:"))
        self.pushButton.setText(_translate("Form2", "LOG IN"))


    def next_page(self):
        n1 = self.lineEdit.text()
        n2 = self.lineEdit_2.text()

        db_connection = sqlite3.connect("organ.db")
        cursor = db_connection.cursor()

        # Execute a query to fetch user details
        query = "SELECT * FROM user_details WHERE USER_NAME=? AND PASSWORD=?"
        cursor.execute(query, (n1, n2))
        result = cursor.fetchone()

        # Check if the result is not None (i.e., credentials match)
        if result is not None:
            self.lineEdit_21.setText("Correct credentials")

            # time.sleep(2)
            self.Form12 = QtWidgets.QMainWindow()
            self.Ui = Ui_Form12()
            self.Ui.setupUi(self.Form12)
            self.Form12.show()
        else:
            self.lineEdit_21.setText("Wrong credentials")

        # Close the database connection for 'user.db'
        cursor.close()
        db_connection.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form22 = QtWidgets.QWidget()
    ui = Ui_Form22()
    ui.setupUi(Form22)
    Form22.show()
    sys.exit(app.exec_())
