# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file 'page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from patient_login import Ui_Form22

con = sqlite3.connect('organ.db')


class Ui_Form3(object):
    def setupUi(self, Form3):
        self.Form3 = Form3  # Store the reference to the main form
        Form3.setObjectName("Form3")
        Form3.resize(800, 600)

        # Set up the background image
        self.label111 = QtWidgets.QLabel(Form3)
        self.label111.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label111.setPixmap(QtGui.QPixmap("333.jpg"))
        self.label111.setScaledContents(True)
        self.label111.setObjectName("label111")

        # Set the background image to be fixed in size
        self.label111.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.label111.setAlignment(QtCore.Qt.AlignCenter)

        self.label = QtWidgets.QLabel(Form3)
        self.label.setGeometry(QtCore.QRect(200, 20, 501, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(198,44,126)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form3)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,255,255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form3)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form3)
        self.label_4.setGeometry(QtCore.QRect(70, 280, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255,255,255);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Form3)
        self.label_6.setGeometry(QtCore.QRect(70, 340, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255,255,255);")
        self.label_6.setObjectName("label_6")
        self.insertinput = QtWidgets.QPushButton(Form3)
        self.insertinput.setGeometry(QtCore.QRect(570, 490, 191, 61))
        self.insertinput.setStyleSheet("font: 19pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(88,202,250);\n"
"color: rgb(0,0,0);\n"
"border-radius:20px;")
        self.insertinput.setObjectName("insertinput")
        self.insertinput.clicked.connect(self.insertData)

        self.nameinput = QtWidgets.QLineEdit(Form3)
        self.nameinput.setGeometry(QtCore.QRect(240, 160, 431, 41))
        self.nameinput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.nameinput.setObjectName("nameinput")

        self.pwdinput = QtWidgets.QLineEdit(Form3)
        self.pwdinput.setGeometry(QtCore.QRect(240, 220, 431, 41))
        self.pwdinput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.pwdinput.setObjectName("pwdinput")

        self.mailinput = QtWidgets.QLineEdit(Form3)
        self.mailinput.setGeometry(QtCore.QRect(240, 280, 431, 41))
        self.mailinput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.mailinput.setObjectName("mailinput")

        self.mobileinput = QtWidgets.QLineEdit(Form3)
        self.mobileinput.setGeometry(QtCore.QRect(240, 340, 431, 41))
        self.mobileinput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.mobileinput.setObjectName("mobileinput")



        self.label_7 = QtWidgets.QLabel(Form3)
        self.label_7.setGeometry(QtCore.QRect(70, 405, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_7.setStyleSheet("color: rgb(255,255,255);")
        self.label_8 = QtWidgets.QLabel(Form3)
        self.label_8.setGeometry(QtCore.QRect(70, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.textEdit = QtWidgets.QTextEdit(Form3)
        self.textEdit.setGeometry(QtCore.QRect(100, 480, 431, 101))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "font: 18pt \"MS Shell Dlg 2\";\n"
                                    "color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)
        Form3.setWindowTitle("Register")


    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Form"))
        self.label.setText(_translate("Form3", "  ENTER DETAILS"))
        self.label_2.setText(_translate("Form3", "Name : "))
        self.label_3.setText(_translate("Form3", "Password:"))
        self.label_4.setText(_translate("Form3", "Mail ID.:"))
        self.label_6.setText(_translate("Form3", "Mobile No.:"))

        self.insertinput.setText(_translate("Form3", "REGISTER"))
        # self.updateinput.setText(_translate("Form3", "outtime"))

    def insertData(self):
        name = self.nameinput.text()
        password = self.pwdinput.text()
        mail = self.mailinput.text()
        mobile = self.mobileinput.text()

        # Check if mobile number consists only of integers and has a length of 10
        if not (mobile.isdigit() and len(mobile) == 10):
            self.updateTextEdit("Error: Mobile number should contain only 10 digits.")
            return

        if not all([name, password, mail, mobile]):
            self.updateTextEdit("Error: Please fill in all the required fields.")
            return

        cursor = con.cursor()
        cursor.execute("INSERT INTO [user_details] (USER_NAME, PASSWORD, MAIL_ID, MOBILE_NO) "
                       "VALUES (?, ?, ?, ?)",
                       (name, password, mail, mobile))
        con.commit()
        cursor.close()

        self.updateTextEdit("Success: Patient registered successfully!")
        # self.Form3.close()

        self.Form22 = QtWidgets.QMainWindow()
        self.Ui = Ui_Form22()
        self.Ui.setupUi(self.Form22)
        self.Form22.show()
        self.Form3.close()

    def updateTextEdit(self, message):
        # Replace the QTextEdit content
        self.textEdit.setPlainText(message)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form3 = QtWidgets.QWidget()
    ui = Ui_Form3()
    ui.setupUi(Form3)
    Form3.show()
    sys.exit(app.exec_())
