# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from patient_login import Ui_Form22
from patient_register import Ui_Form3

class Ui_Form1234(object):
    def setupUi(self, Form1234):
        Form1234.setObjectName("Form1234")
        Form1234.resize(800,600)
        self.label = QtWidgets.QLabel(Form1234)
        self.label.setGeometry(QtCore.QRect(0, 0, 800,600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("23232.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form1234)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 541, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(198,44,126)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form1234)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        # font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form1234)
        self.label_4.setGeometry(QtCore.QRect(50, 360, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form1234)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form1234)
        self.label_6.setGeometry(QtCore.QRect(50, 250, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Form1234)
        self.pushButton.setGeometry(QtCore.QRect(110, 220, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(88,202,250);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.login)

        self.pushButton2 = QtWidgets.QPushButton(Form1234)
        self.pushButton2.setGeometry(QtCore.QRect(510, 220, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("border-radius:30px;\n"
                                      "background-color: rgb(88,202,250);")
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.clicked.connect(self.register)


        self.retranslateUi(Form1234)
        QtCore.QMetaObject.connectSlotsByName(Form1234)
        Form1234.setWindowTitle("Select options")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", " SELECT OPTIONS "))

        self.pushButton.setText(_translate("Form", "LOGIN"))
        self.pushButton2.setText(_translate("Form", "REGISTER"))


    def login(self):
        print("hello")
        self.Form22 = QtWidgets.QMainWindow()
        self.Ui = Ui_Form22()
        self.Ui.setupUi(self.Form22)
        self.Form22.show()


    def register(self):
        print("hello")
        self.Form3 = QtWidgets.QMainWindow()
        self.Ui = Ui_Form3()
        self.Ui.setupUi(self.Form3)
        self.Form3.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1234 = QtWidgets.QWidget()
    ui = Ui_Form1234()
    ui.setupUi(Form1234)
    Form1234.show()
    sys.exit(app.exec_())
